[project]
name = "emotions-classification"
version = "0.1.0"
description = "Classification model to classify social media comments undeer post by emotions"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dvc>=3.65.0",
]
